services:
  pdf-chat-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
    depends_on:
      - ollama-service

  ollama-service:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./pull-model.sh:/pull-model.sh:ro
    entrypoint: ["/bin/bash", "/pull-model.sh"]
    ports:
      - "11434:11434"

volumes:
  ollama_data:
